/**
 * hooks/mandi/usePayments.ts
 *
 * Phase 6: Payments & Receipts hooks.
 * Powers the /finance/payments page and inline payment dialogs.
 *
 * Key design: every createPayment() call REQUIRES an idempotency_key
 * generated by the caller (crypto.randomUUID() in the form component).
 * This prevents double-submission on retry.
 */
"use client"

import { useState, useEffect, useCallback } from "react"
import { useToast } from "@/hooks/use-toast"
import type { CreatePaymentDTO, Payment } from "@/../packages/contracts/src"

export interface PaymentFilters {
  page?: number
  limit?: number
  payment_type?: 'payment' | 'receipt'
  party_id?: string
  date_from?: string
  date_to?: string
}

// ── usePaymentsList ───────────────────────────────────────────────────────────

export function usePaymentsList(filters: PaymentFilters = {}) {
  const [payments, setPayments] = useState<Payment[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const fetchPayments = useCallback(async () => {
    setLoading(true)
    try {
      const params = new URLSearchParams()
      if (filters.page) params.set('page', String(filters.page))
      if (filters.limit) params.set('limit', String(filters.limit))
      if (filters.payment_type) params.set('payment_type', filters.payment_type)
      if (filters.party_id) params.set('party_id', filters.party_id)
      if (filters.date_from) params.set('date_from', filters.date_from)
      if (filters.date_to) params.set('date_to', filters.date_to)

      const res = await fetch(`/api/mandi/payments?${params}`)
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const json = await res.json()
      setPayments(json.data ?? [])
      setTotal(json.total ?? 0)
      setError(null)
    } catch {
      setError('Failed to load payments')
    } finally {
      setLoading(false)
    }
  }, [filters.page, filters.limit, filters.payment_type, filters.party_id, filters.date_from, filters.date_to])

  useEffect(() => { fetchPayments() }, [fetchPayments])
  return { payments, total, loading, error, refetch: fetchPayments }
}

// ── useCreatePayment ──────────────────────────────────────────────────────────

export function useCreatePayment(onSuccess?: (payment: Payment) => void) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const { toast } = useToast()

  const createPayment = useCallback(async (dto: CreatePaymentDTO): Promise<Payment | null> => {
    if (!dto.idempotency_key) {
      toast({ title: 'Dev Error', description: 'idempotency_key is required', variant: 'destructive' })
      return null
    }

    setLoading(true)
    setError(null)
    try {
      const res = await fetch('/api/mandi/payments', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(dto),
      })
      const data = await res.json()
      if (!res.ok) {
        // 409 = duplicate idempotency key — safe to treat as success
        if (res.status === 409) {
          toast({ title: '⚠️ Duplicate Request', description: 'This payment was already recorded', variant: 'default' })
          return null
        }
        const msg = data.error ?? `Error ${res.status}`
        setError(msg)
        toast({ title: 'Payment Failed', description: msg, variant: 'destructive' })
        return null
      }
      toast({
        title: dto.payment_type === 'receipt' ? '✅ Receipt Recorded' : '✅ Payment Recorded',
        description: `₹${dto.amount.toLocaleString('en-IN')} ${dto.payment_mode}`
      })
      onSuccess?.(data as Payment)
      return data as Payment
    } catch {
      const msg = 'Network error — payment not saved'
      setError(msg)
      toast({ title: 'Network Error', description: msg, variant: 'destructive' })
      return null
    } finally {
      setLoading(false)
    }
  }, [onSuccess, toast])

  return { createPayment, loading, error }
}
